#!/bin/bash
# Quick Commands for Steven

echo "🚨 GEMINI LEGION EMERGENCY COMMANDS"
echo "=================================="
echo ""
echo "1. Apply Emergency Fix:"
echo "   python3 emergency_fix.py"
echo ""
echo "2. Restart Backend:"
echo "   # Kill current process (Ctrl+C or find PID and kill)"
echo "   cd /Users/ttig/downloads/geminopus-branch"
echo "   python3 -m gemini_legion_backend.main"
echo ""
echo "3. Test Simple Message (no duplication):"
echo "   curl -X POST http://localhost:8000/api/channels/test_simple \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"channel_id\": \"general\", \"content\": \"Test message\"}'"
echo ""
echo "4. Create New Channel:"
echo "   curl -X POST http://localhost:8000/api/channels/create \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"name\": \"test_channel\", \"channel_type\": \"public\"}'"
echo ""
echo "5. List Channels:"
echo "   curl http://localhost:8000/api/channels/"
echo ""
echo "6. Check Health:"
echo "   curl http://localhost:8000/api/health"
echo ""
echo "=================================="
echo "📚 Important Files:"
echo "- README_STEVEN.md - Start here"
echo "- UNFUCK_PLAN.md - 4-week refactor plan"
echo "- emergency_fix.py - Stop duplication NOW"
echo "- IDEAL_ARCHITECTURE_DESIGN_DOCUMENT.md - The goal"
